### ISSUE TITLE
Pluginmanager crashes after rabbitmq timeout

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/son-mano-framework#225]
I've noticed that the pluginmanager stops working if it can't connect to rabbitmq.

Is there a way to handle the exception and retry the connection without die?

Example log here:
```
13:46:01 + docker logs test.pluginmanager
13:46:01 INFO:son-mano-pluginmanger:model:Connected to MongoDB 'sonata-plugin-manager'@mongo:27017
13:46:01 INFO:son-mano-pluginmanger:model:Cleared DB 'sonata-plugin-manager'
13:46:01 INFO:son-mano-pluginmanger:interface:Started management REST interface @ http://0.0.0.0:8001
13:46:01 INFO:son-mano-base:plugin:Starting MANO Plugin: 'son-plugin.SonPluginManager' ...
13:46:01 Traceback (most recent call last):
13:46:01   File "/usr/local/bin/son-mano-pluginmanager", line 11, in <module>
13:46:01     load_entry_point('son-mano-pluginmanager', 'console_scripts', 'son-mano-pluginmanager')()
13:46:01   File "/son-mano-pluginmanager/son_mano_pluginmanager/__main__.py", line 33, in main
13:46:01     pluginmanager.main()
13:46:01   File "/son-mano-pluginmanager/son_mano_pluginmanager/pluginmanager.py", line 212, in main
13:46:01     SonPluginManager()
13:46:01   File "/son-mano-pluginmanager/son_mano_pluginmanager/pluginmanager.py", line 67, in __init__
13:46:01     auto_heartbeat_rate=0)
13:46:01   File "/usr/local/lib/python3.4/site-packages/sonmanobase-0.9-py3.4.egg/sonmanobase/plugin.py", line 82, in __init__
13:46:01   File "/usr/local/lib/python3.4/site-packages/sonmanobase-0.9-py3.4.egg/sonmanobase/messaging.py", line 234, in __init__
13:46:01   File "/usr/local/lib/python3.4/site-packages/sonmanobase-0.9-py3.4.egg/sonmanobase/messaging.py", line 68, in __init__
13:46:01   File "/usr/local/lib/python3.4/site-packages/sonmanobase-0.9-py3.4.egg/sonmanobase/messaging.py", line 79, in setup_connection
13:46:01   File "/usr/local/lib/python3.4/site-packages/AMQPStorm-2.2.2-py3.4.egg/amqpstorm/uri_connection.py", line 46, in __init__
13:46:01   File "/usr/local/lib/python3.4/site-packages/AMQPStorm-2.2.2-py3.4.egg/amqpstorm/connection.py", line 70, in __init__
13:46:01   File "/usr/local/lib/python3.4/site-packages/AMQPStorm-2.2.2-py3.4.egg/amqpstorm/connection.py", line 190, in open
13:46:01   File "/usr/local/lib/python3.4/site-packages/AMQPStorm-2.2.2-py3.4.egg/amqpstorm/io.py", line 100, in open
13:46:01   File "/usr/local/lib/python3.4/site-packages/AMQPStorm-2.2.2-py3.4.egg/amqpstorm/io.py", line 171, in _find_address_and_connect
13:46:01 amqpstorm.exception.AMQPConnectionError: Could not connect to broker:5672
```

**Comment by tsoenen** [comment]
Fixed. All plugins are now waiting until the broker is available, without crashing.
